common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: gameway_dev

test:
  <<: *common
  database: gameway_test

production:
  <<: *common
  database: gameway
